### ISSUE TITLE
Upload list link had two slashes

### ISSUE THREAD

**Issue by Pips801** [UploadX/UploadX#2]
https://pips.rocks/JOy

**Comment by NullOrNaN** [comment]
I'm not sure this is a bug to be honest.. it works either way.

**Comment by Pips801** [comment]
#7 should be fixed here

**Comment by NullOrNaN** [comment]
That still doesn't answer why it's a bug - the extra / isn't required from what I recall.

**Comment by Pips801** [comment]
You're right, it isn't required. It's pointless, and a bug. 
You know, a bug is when something happens that's not supposed to happen. whether there is 1 extra / or 10 in the url, it makes no difference. There should only be one, especially when part of the point of the software is to make URLs shorter than say imgur or puush, it starts to defeat the purpose when there's suddenly an extra unnecessary character being added to every page you visit through the admin panel.

Saying "it works either way" isn't a great way of addressing a problem. "yeah sure it spews out errors and reveals PII, but it works either way."
